a=("helicopter")
print(len(a))
first=(7)
secont=(4)
third=(5)
summa=(first+secont)
diff=(first-secont)
print(summa, diff)
mean=((first+secont+third)/3)
print(mean)
first_string=("Вторник")
secont_string=("Понедельник")
print(secont_string,first_string,sep=', ')
a=(3)
b=(2)
c=(4)
f=(a*b)+(a*c)
print(f)
