a=("helicopter")
print(len(a))
first=(7)
secont=(4)
third=(5)
summa=(print(first+secont))
diff=(print(first-secont))
mean=(print((first+secont+third)/3))
first_string=("Вторник")
secont_string=("Понедельник")
print(secont_string,first_string,sep=', ')
a=(3)
b=(2)
c=(4)
f=(print((a*b)+(a*c)))